# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7b6917cb73b96b86444df990c90d44f3b0ba7ac75f7b59e16f57d09581dd8a401afed520208b4ef0a5554980d9facf4b29956e59f269ccf5700f0814fdcc8162

test:
  secret_key_base: 65d77b5087533750ec39205333a6714f321f840ef9dcdcb6be8ded69d8960f316051320b9309518b2251f303522fc0b1cbb2e5d9d5be590e84546cc7b8c681ba

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
